### ISSUE TITLE
Mod not listed Exception

### ISSUE THREAD

**Issue by cat24max** [alliance-apps/VeniceRCON-backend#14]
ModNotListed should be a HTTP error and not an Error that will crash the request.

DELETE http://localhost:8000/api/instances/1/mods/gameadmin

(Caused by VU capitalization error, but should still be catched)

  Error: ModNotListed: modList.Remove gameadmin
      at /mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/vu-rcon/lib/transport/Request.js:72:27
      at new Promise (<anonymous>)
      at Request.send (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/vu-rcon/lib/transport/Request.js:71:16)
      at Battlefield.delMod (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/vu-rcon/lib/Battlefield.js:627:59)
      at /mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/lib/services/koa/api/instances/mods/mod.js:15:42
      at dispatch (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/@koa/router/node_modules/koa-compose/index.js:44:32)
      at next (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/@koa/router/node_modules/koa-compose/index.js:45:18)
      at /mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/lib/services/koa/permission.js:19:15
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async validator (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/koa-joi-router/joi-router.js:407:32)
      at async noopMiddleware (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/koa-joi-router/joi-router.js:267:10)
      at async specExposer (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/koa-joi-router/joi-router.js:448:5)
      at async prepareRequest (/mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/node_modules/koa-joi-router/joi-router.js:460:3)
      at async /mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/lib/services/koa/api/instances/mods/index.js:44:5
      at async /mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/lib/services/koa/api/instances/index.js:65:9
      at async /mnt/c/Users/Tim/Documents/GitHub/VeniceRCON-backend/lib/services/koa/api/instances/mods/index.js:17:5

**Comment by Multivit4min** [comment]
fixed with #16f67aa5d9d1361bd7f532988341bfd6eca3afc2

**Comment by Multivit4min** [comment]
fixed with 16f67aa5d9d1361bd7f532988341bfd6eca3afc2
